//
//  WordMaker.swift
//  MagneticPoetry
//
//  Created by Noah Brauner on 11/21/20.
//

import Foundation

class WordMaker {
    
    static let shared = WordMaker()
    
    private init () {}
    
    public func getNewWords(of type: PartOfSpeech?) -> [NewWordModel] {
        var newWordModels = [NewWordModel]()
        
        let words = getWords()
        
        if type == nil {
            let alpabetizedWords = words.sorted { $0.word.lowercased() < $1.word.lowercased() }
            for word in alpabetizedWords {
                let model = NewWordModel(word: word.word)
                newWordModels.append(model)
            }
        }
        else {
            var posSortedWords = [Word]()
            for word in words {
                if word.partOfSpeech.contains(type!) {
                    posSortedWords.append(word)
                }
            }
            let alpabetizedWords = posSortedWords.sorted { $0.word.lowercased() < $1.word.lowercased() }
            
            for word in alpabetizedWords {
                let model = NewWordModel(word: word.word)
                newWordModels.append(model)
            }
        }
        return newWordModels
    }
    
    public func getWords() -> [Word] {
        return [
            Word(word: "something", partOfSpeech: [.noun]),
            Word(word: "very", partOfSpeech: [.adverb]),
            Word(word: "chair", partOfSpeech: [.noun]),
            Word(word: "born", partOfSpeech: [.verb]),
            Word(word: "too", partOfSpeech: [.adverb]),
            Word(word: "ear", partOfSpeech: [.noun]),
            Word(word: "black", partOfSpeech: [.adjective, .noun]),
            Word(word: "hide", partOfSpeech: [.verb]),
            Word(word: "dug", partOfSpeech: [.verb]),
            Word(word: "came", partOfSpeech: [.verb]),
            Word(word: "when", partOfSpeech: [.adverb]),
            Word(word: "there", partOfSpeech: [.other]),
            Word(word: "see", partOfSpeech: [.verb]),
            Word(word: "grow", partOfSpeech: [.verb]),
            Word(word: "ask", partOfSpeech: [.verb]),
            Word(word: "cried", partOfSpeech: [.verb]),
            Word(word: "on", partOfSpeech: [.preposistion]),
            Word(word: "and", partOfSpeech: [.other]),
            Word(word: "whisper", partOfSpeech: [.verb]),
            Word(word: "for", partOfSpeech: [.preposistion]),
            Word(word: "clever", partOfSpeech: [.adjective]),
            Word(word: "bird", partOfSpeech: [.noun]),
            Word(word: "wish", partOfSpeech: [.noun, .verb]),
            Word(word: "thought", partOfSpeech: [.verb]),
            Word(word: "like", partOfSpeech: [.preposistion]),
            Word(word: "castle", partOfSpeech: [.noun]),
            Word(word: "rainbow", partOfSpeech: [.noun]),
            Word(word: "warm", partOfSpeech: [.adjective]),
            Word(word: "with", partOfSpeech: [.preposistion]),
            Word(word: "nest", partOfSpeech: [.noun]),
            Word(word: "a", partOfSpeech: [.other]),
            Word(word: "winter", partOfSpeech: [.noun]),
            Word(word: "I", partOfSpeech: [.pronoun]),
            Word(word: "bike", partOfSpeech: [.noun]),
            Word(word: "flew", partOfSpeech: [.verb]),
            Word(word: "in", partOfSpeech: [.preposistion]),
            Word(word: "wind", partOfSpeech: [.noun, .verb]),
            Word(word: "day", partOfSpeech: [.noun]),
            Word(word: "down", partOfSpeech: [.preposistion]),
            Word(word: "us", partOfSpeech: [.pronoun]),
            Word(word: "went", partOfSpeech: [.verb]),
            Word(word: "pumpkin", partOfSpeech: [.noun]),
            Word(word: "quiet", partOfSpeech: [.adjective]),
            Word(word: "have", partOfSpeech: [.verb]),
            Word(word: "tell", partOfSpeech: [.verb]),
            Word(word: "round", partOfSpeech: [.adjective, .noun]),
            Word(word: "pig", partOfSpeech: [.noun]),
            Word(word: "many", partOfSpeech: [.adjective]),
            Word(word: "show", partOfSpeech: [.noun, .verb]),
            Word(word: "mad", partOfSpeech: [.adjective]),
            Word(word: "the", partOfSpeech: [.other]),
            Word(word: "we", partOfSpeech: [.pronoun]),
            Word(word: "top", partOfSpeech: [.adjective]),
            Word(word: "my", partOfSpeech: [.pronoun]),
            Word(word: "is", partOfSpeech: [.verb]),
            Word(word: "each", partOfSpeech: [.other]),
            Word(word: "dog", partOfSpeech: [.noun]),
            Word(word: "ghost", partOfSpeech: [.noun]),
            Word(word: "draw", partOfSpeech: [.noun, .verb]),
            Word(word: "not", partOfSpeech: [.adverb]),
            Word(word: "funny", partOfSpeech: [.adjective]),
            Word(word: "girl", partOfSpeech: [.noun]),
            Word(word: "town", partOfSpeech: [.noun]),
            Word(word: "are", partOfSpeech: [.verb]),
            Word(word: "name", partOfSpeech: [.noun]),
            Word(word: "man", partOfSpeech: [.noun]),
            Word(word: "he", partOfSpeech: [.pronoun]),
            Word(word: "of", partOfSpeech: [.preposistion]),
            Word(word: "mirror", partOfSpeech: [.noun, .verb]),
            Word(word: "silly", partOfSpeech: [.adjective]),
            Word(word: "their", partOfSpeech: [.pronoun]),
            Word(word: "because", partOfSpeech: [.preposistion]),
            Word(word: "woman", partOfSpeech: [.noun]),
            Word(word: "has", partOfSpeech: [.verb]),
            Word(word: "family", partOfSpeech: [.noun]),
            Word(word: "garden", partOfSpeech: [.noun]),
            Word(word: "about", partOfSpeech: [.preposistion]),
            Word(word: "flower", partOfSpeech: [.noun]),
            Word(word: "queen", partOfSpeech: [.noun]),
            Word(word: "stop", partOfSpeech: [.verb]),
            Word(word: "get", partOfSpeech: [.verb]),
            Word(word: "fish", partOfSpeech: [.noun, .verb]),
            Word(word: "think", partOfSpeech: [.verb]),
            Word(word: "birthday", partOfSpeech: [.noun]),
            Word(word: "animal", partOfSpeech: [.noun]),
            Word(word: "an", partOfSpeech: [.other]),
            Word(word: "read", partOfSpeech: [.noun, .verb]),
            Word(word: "wrote", partOfSpeech: [.verb]),
            Word(word: "you", partOfSpeech: [.pronoun]),
            Word(word: "laugh", partOfSpeech: [.noun, .verb]),
            Word(word: "believe", partOfSpeech: [.verb]),
            Word(word: "important", partOfSpeech: [.adjective]),
            Word(word: "gentle", partOfSpeech: [.adjective]),
            Word(word: "fed", partOfSpeech: [.noun]),
            Word(word: "good", partOfSpeech: [.adjective]),
            Word(word: "inside", partOfSpeech: [.preposistion]),
            Word(word: "sad", partOfSpeech: [.adjective]),
            Word(word: "color", partOfSpeech: [.noun, .verb]),
            Word(word: "song", partOfSpeech: [.noun]),
            Word(word: "me", partOfSpeech: [.pronoun]),
            Word(word: "child", partOfSpeech: [.noun]),
            Word(word: "but", partOfSpeech: [.other]),
            Word(word: "up", partOfSpeech: [.adverb]),
            Word(word: "under", partOfSpeech: [.preposistion]),
            Word(word: "talk", partOfSpeech: [.noun, .verb]),
            Word(word: "take", partOfSpeech: [.verb]),
            Word(word: "wild", partOfSpeech: [.adjective]),
            Word(word: "glad", partOfSpeech: [.adjective]),
            Word(word: "play", partOfSpeech: [.noun, .verb]),
            Word(word: "to", partOfSpeech: [.other]),
            Word(word: "spring", partOfSpeech: [.noun, .verb]),
            Word(word: "say", partOfSpeech: [.verb]),
            Word(word: "or", partOfSpeech: [.other]),
            Word(word: "she", partOfSpeech: [.pronoun]),
            Word(word: "candy", partOfSpeech: [.noun]),
            Word(word: "cry", partOfSpeech: [.noun, .verb]),
            Word(word: "mountain", partOfSpeech: [.noun]),
            Word(word: "could", partOfSpeech: [.verb]),
            Word(word: "teacher", partOfSpeech: [.noun]),
            Word(word: "book", partOfSpeech: [.noun]),
            Word(word: "they", partOfSpeech: [.pronoun]),
            Word(word: "ball", partOfSpeech: [.noun]),
            Word(word: "butterfly", partOfSpeech: [.noun]),
            Word(word: "special", partOfSpeech: [.adjective]),
            Word(word: "king", partOfSpeech: [.noun]),
            Word(word: "bug", partOfSpeech: [.noun]),
            Word(word: "baby", partOfSpeech: [.noun]),
            Word(word: "monster", partOfSpeech: [.noun]),
            Word(word: "owl", partOfSpeech: [.noun]),
            Word(word: "lesson", partOfSpeech: [.noun]),
            Word(word: "how", partOfSpeech: [.adverb]),
            Word(word: "&", partOfSpeech: [.other]),
            Word(word: "once", partOfSpeech: [.adverb]),
            Word(word: "window", partOfSpeech: [.noun]),
            Word(word: "slow", partOfSpeech: [.adjective]),
            Word(word: "tiger", partOfSpeech: [.noun]),
            Word(word: "storm", partOfSpeech: [.noun, .verb]),
            Word(word: "dinner", partOfSpeech: [.noun]),
            Word(word: "noon", partOfSpeech: [.noun]),
            Word(word: "balloon", partOfSpeech: [.noun]),
            Word(word: "over", partOfSpeech: [.preposistion]),
            Word(word: "new", partOfSpeech: [.adjective]),
            Word(word: "leave", partOfSpeech: [.noun, .verb]),
            Word(word: "farm", partOfSpeech: [.noun, .verb]),
            Word(word: "nose", partOfSpeech: [.noun]),
            Word(word: "sun", partOfSpeech: [.noun]),
            Word(word: "star", partOfSpeech: [.noun, .adjective]),
            Word(word: "yes", partOfSpeech: [.adverb]),
            Word(word: "prince", partOfSpeech: [.noun]),
            Word(word: "honor", partOfSpeech: [.noun]),
            Word(word: "fast", partOfSpeech: [.adverb]),
            Word(word: "more", partOfSpeech: [.adverb]),
            Word(word: "hot", partOfSpeech: [.adjective]),
            Word(word: "hand", partOfSpeech: [.noun, .verb]),
            Word(word: "her", partOfSpeech: [.pronoun]),
            Word(word: "sea", partOfSpeech: [.noun]),
            Word(word: "who", partOfSpeech: [.pronoun]),
            Word(word: "next", partOfSpeech: [.preposistion]),
            Word(word: "story", partOfSpeech: [.noun]),
            Word(word: "ride", partOfSpeech: [.noun, .verb]),
            Word(word: "always", partOfSpeech: [.adverb]),
            Word(word: "corn", partOfSpeech: [.noun]),
            Word(word: "snake", partOfSpeech: [.noun]),
            Word(word: "through", partOfSpeech: [.preposistion]),
            Word(word: "barn", partOfSpeech: [.noun]),
            Word(word: "mud", partOfSpeech: [.noun]),
            Word(word: "help", partOfSpeech: [.noun, .verb]),
            Word(word: "as", partOfSpeech: [.preposistion]),
            Word(word: "bite", partOfSpeech: [.noun, .verb]),
            Word(word: "home", partOfSpeech: [.noun]),
            Word(word: "upon", partOfSpeech: [.preposistion]),
            Word(word: "boy", partOfSpeech: [.noun]),
            Word(word: "box", partOfSpeech: [.noun]),
            Word(word: "try", partOfSpeech: [.verb]),
            Word(word: "ate", partOfSpeech: [.verb]),
            Word(word: "pink", partOfSpeech: [.adjective]),
            Word(word: "dinosaur", partOfSpeech: [.noun]),
            Word(word: "cow", partOfSpeech: [.noun]),
            Word(word: "put", partOfSpeech: [.verb]),
            Word(word: "live", partOfSpeech: [.adjective, .verb]),
            Word(word: "yellow", partOfSpeech: [.adjective]),
            Word(word: "phone", partOfSpeech: [.noun]),
            Word(word: "brother", partOfSpeech: [.noun]),
            Word(word: "tree", partOfSpeech: [.noun]),
            Word(word: "it", partOfSpeech: [.pronoun]),
            Word(word: "elephant", partOfSpeech: [.noun]),
            Word(word: "easy", partOfSpeech: [.adjective]),
            Word(word: "were", partOfSpeech: [.verb]),
            Word(word: "snow", partOfSpeech: [.noun, .verb]),
            Word(word: "do", partOfSpeech: [.verb]),
            Word(word: "little", partOfSpeech: [.adjective]),
            Word(word: "kind", partOfSpeech: [.noun]),
            Word(word: "truth", partOfSpeech: [.noun]),
            Word(word: "joy", partOfSpeech: [.noun]),
            Word(word: "moon", partOfSpeech: [.noun]),
            Word(word: "fun", partOfSpeech: [.noun]),
            Word(word: "which", partOfSpeech: [.other]),
            Word(word: "where", partOfSpeech: [.adverb]),
            Word(word: "rain", partOfSpeech: [.noun, .verb]),
            Word(word: "red", partOfSpeech: [.adjective]),
            Word(word: "am", partOfSpeech: [.verb]),
            Word(word: "pretend", partOfSpeech: [.adjective, .verb]),
            Word(word: "fat", partOfSpeech: [.noun, .adjective]),
            Word(word: "had", partOfSpeech: [.verb]),
            Word(word: "cool", partOfSpeech: [.adjective]),
            Word(word: "his", partOfSpeech: [.pronoun]),
            Word(word: "ring", partOfSpeech: [.noun, .verb]),
            Word(word: "morning", partOfSpeech: [.noun]),
            Word(word: "out", partOfSpeech: [.preposistion]),
            Word(word: "sing", partOfSpeech: [.verb]),
            Word(word: "what", partOfSpeech: [.pronoun]),
            Word(word: "fall", partOfSpeech: [.noun, .verb]),
            Word(word: "wonder", partOfSpeech: [.noun, .verb]),
            Word(word: "mom", partOfSpeech: [.noun]),
            Word(word: "summer", partOfSpeech: [.noun]),
            Word(word: "toy", partOfSpeech: [.noun]),
            Word(word: "told", partOfSpeech: [.verb]),
            Word(word: "peace", partOfSpeech: [.noun]),
            Word(word: "big", partOfSpeech: [.adjective]),
            Word(word: "light", partOfSpeech: [.adjective]),
            Word(word: "world", partOfSpeech: [.noun]),
            Word(word: "pool", partOfSpeech: [.noun]),
            Word(word: "sky", partOfSpeech: [.noun]),
            Word(word: "that", partOfSpeech: [.other]),
            Word(word: "boat", partOfSpeech: [.noun]),
            Word(word: "way", partOfSpeech: [.noun]),
            Word(word: "from", partOfSpeech: [.preposistion]),
            Word(word: "your", partOfSpeech: [.pronoun]),
            Word(word: "never", partOfSpeech: [.adverb]),
            Word(word: "remember", partOfSpeech: [.verb]),
            Word(word: "know", partOfSpeech: [.verb]),
            Word(word: "all", partOfSpeech: [.other]),
            Word(word: "begin", partOfSpeech: [.verb]),
            Word(word: "if", partOfSpeech: [.preposistion]),
            Word(word: "dark", partOfSpeech: [.noun, .adjective]),
            Word(word: "was", partOfSpeech: [.verb]),
            Word(word: "want", partOfSpeech: [.verb]),
            Word(word: "dream", partOfSpeech: [.noun, .verb]),
            Word(word: "start", partOfSpeech: [.adjective, .verb]),
            Word(word: "old", partOfSpeech: [.adjective]),
            Word(word: "sister", partOfSpeech: [.noun]),
            Word(word: "dad", partOfSpeech: [.noun]),
            Word(word: "princess", partOfSpeech: [.noun]),
            Word(word: "will", partOfSpeech: [.verb]),
            Word(word: "monkey", partOfSpeech: [.noun]),
            Word(word: "hat", partOfSpeech: [.noun]),
            Word(word: "no", partOfSpeech: [.other]),
            Word(word: "water", partOfSpeech: [.noun]),
            Word(word: "here", partOfSpeech: [.adverb]),
            Word(word: "fly", partOfSpeech: [.verb, .noun]),
            Word(word: "love", partOfSpeech: [.noun, .verb, .adjective]),
            Word(word: "understand", partOfSpeech: [.verb]),
            Word(word: "give", partOfSpeech: [.verb]),
            Word(word: "time", partOfSpeech: [.noun, .verb]),
            Word(word: "cat", partOfSpeech: [.noun]),
            Word(word: "said", partOfSpeech: [.verb]),
            Word(word: "happy", partOfSpeech: [.adjective]),
            Word(word: "sail", partOfSpeech: [.noun, .verb]),
            Word(word: "glow", partOfSpeech: [.noun, .verb]),
            Word(word: "blue", partOfSpeech: [.adjective]),
            Word(word: "pull", partOfSpeech: [.noun, .verb]),
            Word(word: "go", partOfSpeech: [.verb]),
            Word(word: "saw", partOfSpeech: [.noun, .verb]),
            Word(word: "eat", partOfSpeech: [.verb]),
            Word(word: "hold", partOfSpeech: [.verb]),
            Word(word: "run", partOfSpeech: [.noun, .verb]),
            Word(word: "one", partOfSpeech: [.other]),
            Word(word: "wing", partOfSpeech: [.noun, .verb]),
            Word(word: "does", partOfSpeech: [.verb]),
            Word(word: "so", partOfSpeech: [.adverb]),
            Word(word: "roar", partOfSpeech: [.noun, .verb]),
            Word(word: "jump", partOfSpeech: [.noun, .verb]),
            Word(word: "swim", partOfSpeech: [.noun, .verb]),
            Word(word: "lake", partOfSpeech: [.noun]),
            Word(word: "walk", partOfSpeech: [.noun, .verb]),
            Word(word: "bring", partOfSpeech: [.verb]),
            Word(word: "turn", partOfSpeech: [.verb]),
            Word(word: "feet", partOfSpeech: [.noun]),
            Word(word: "end", partOfSpeech: [.noun])
        ]
    }
}

